POST http://localhost:5002/videojuegos/actualizar
Content-Type: application/json

{
    "id" : 6,
    "nombre" : "Red Dead 1",
    "categoria" : "Acción",
    "plataformas" : ["PC", "PS5"],
    "fecha" : "01-10-2020",
    "estado" : "Nuevo"
}
